# Generated by Django 5.0.6 on 2024-07-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('Nowy', 'Nowy'), ('W toku', 'W toku'), ('Rozwiazany', 'Rozwiazany')], default='Nowy', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Nowy', 'Nowy'), ('W toku', 'W toku'), ('Rozwiazany', 'Rozwiazany')], default='Nowy', max_length=20),
        ),
    ]
